name: Sphinx Build

on: 
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "src_docs/"
          pre-build-command: "pip install sphinx_rtd_theme"
          build-command: "sphinx-build -b html ./source ../docs"

      # .nojekyll file must exist in docs

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: 'docs'
          author_name: GitHub Action
          author_email: magnus@users.noreply.github.com

          branch: docs

          branch_mode: create
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
                