name: Sphinx Build

on: 
  push:
    branches: 
      - ghactions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "src_docs/"
          pre-build-command: "pip install sphinx_rtd_theme"
          build-command: "sphinx-build -b html ./source ../docs"

      # .nojekyll file must exist in docs